=== rothsandro/eleventy-notes/.app/app.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Eleventy Notes Configuration",
  "description": "App configuration for Eleventy Notes",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "The title of the app.",
      "default": "Notes"
    },
    "description": {
      "type": "string",
      "description": "The description of the app, used by search engines",
      "default": "Notes app"
    },
    "theme": {
      "type": "object",
      "description": "The configuration for the theme of the app",
      "default": { "color": "sky" },
      "properties": {
        "color": {
          "type": "string",
          "description": "The primary color of the app",
          "enum": [
            "tomato",
            "red",
            "crimson",
            "pink",
            "plum",
            "purple",
            "violet",
            "indigo",
            "blue",
            "sky",
            "cyan",
            "teal",
            "mint",
            "green",
            "grass",
            "lime",
            "yellow",
            "amber",
            "orange",
            "brown"
          ],
          "default": "sky"
        }
      }
    },
    "editThisNote": {
      "type": "object",
      "description": "The configuration for the \"Edit this note\" link that redirects to the repo where the notes are stored and allows users to edit the note.",
      "required": ["url"],
      "properties": {
        "url": {
          "type": "string",
          "description": "The URL to edit the note. Supported placeholders: {{file}} and {{branch}}"
        },
        "openInNewTab": {
          "type": "boolean",
          "description": "Whether to open the edit link in a new tab",
          "default": false
        }
      }
    },
    "sidebar": {
      "type": "object",
      "description": "The configuration for the sidebar (navigation)",
      "properties": {
        "links": {
          "type": "array",
          "default": [],
          "description": "A list of links that are displayed after the main navigation",
          "items": {
            "type": "object",
            "description": "A link to display in the sidebar",
            "required": ["url", "label", "icon"],
            "properties": {
              "url": {
                "type": "string",
                "description": "The URL of the link"
              },
              "label": {
                "type": "string",
                "description": "The displayed label of the link"
              },
              "icon": {
                "type": "string",
                "description": "The icon of the link, see https://feathericons.com/ for a list of icons"
              },
              "openInNewTab": {
                "type": "boolean",
                "description": "Whether to open the link in a new tab",
                "default": true
              }
            }
          }
        },
        "notes": {
          "type": "array",
          "default": [{}],
          "description": "A list of grouped notes that are displayed in the sidebar",
          "items": {
            "type": "object",
            "description": "A group of notes to display in the sidebar",
            "properties": {
              "pattern": {
                "type": "string",
                "description": "A RegEx pattern to match notes to display in this group"
              },
              "label": {
                "type": "string",
                "description": "The label of the group"
              },
              "tags": {
                "type": "array",
                "description": "A list of tags to match notes",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== rothsandro/eleventy-notes/app.json
{
  "$schema": ".app/app.schema.json",
  "title": "Eleventy Notes",
  "description": "A simple, lightweight, and flexible note-taking template for Eleventy.",
  "editThisNote": {
    "url": "https://github.com/rothsandro/eleventy-notes/edit/{{branch}}/{{file}}"
  },
  "sidebar": {
    "links": [
      {
        "url": "https://github.com/rothsandro/eleventy-notes",
        "label": "GitHub / Support",
        "icon": "github"
      }
    ],
    "notes": [
      {
        "pattern": "^/[^/]+$",
        "label": ""
      },
      {
        "pattern": "^/Releases/",
        "label": "Releases"
      },
      {
        "pattern": "^/Features/",
        "label": "Features",
        "tree": {
          "replace": {
            "^/Features": ""
          }
        }
      },
      {
        "pattern": "^/Deployment/",
        "label": "Deployment"
      }
    ]
  }
}
